export const CATEGORIES = [
  { "name": "Electronics", "color": "blue" },
  { "name": "Cars & Trucks", "color": "indigo" },
  { "name": "Motorcycles", "color": "indigo" },
  { "name": "Boats & Marine", "color": "indigo" },
  { "name": "RVs & Campers", "color": "indigo" },
  { "name": "Houses for Sale", "color": "orange" },
  { "name": "Apartments for Rent", "color": "orange" },
  { "name": "Commercial Property", "color": "orange" },
  { "name": "Vacation Rentals", "color": "orange" },
  { "name": "Jobs", "color": "cyan" },
  { "name": "Services", "color": "purple" },
  { "name": "Fashion", "color": "pink" },
  { "name": "Home & Garden", "color": "green" },
  { "name": "Sports", "color": "red" },
  { "name": "Books", "color": "yellow" },
  { "name": "Pets", "color": "amber" },
  { "name": "Food & Dining", "color": "lime" },
  { "name": "Travel & Resorts", "color": "sky" },
  { "name": "Deals & Offers", "color": "emerald" },
  { "name": "Tickets", "color": "violet" },
  { "name": "Events & Shows", "color": "rose" },
  { "name": "Auction", "color": "fuchsia" },
  { "name": "Buy & Sell", "color": "slate" },
  { "name": "Notices", "color": "teal" },
  { "name": "Health & Beauty", "color": "pink" },
  { "name": "Baby & Kids", "color": "rose" },
  { "name": "Arts & Crafts", "color": "purple" },
  { "name": "Musical Instruments", "color": "violet" },
  { "name": "Office Supplies", "color": "slate" },
  { "name": "Digital Products", "color": "cyan" },
  { "name": "Software & Apps", "color": "blue" },
  { "name": "Tutoring & Lessons", "color": "emerald" },
  { "name": "Home Repair", "color": "amber" },
  { "name": "Free", "color": "green" },
  { "name": "Other", "color": "gray" }
];