// Category-wise field mapping for dynamic ad forms
// Generated from category wise field.csv

export const categoryFields = {
  "Electronics": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images", "Brand/Model", "Year", "Mileage"],
  "Cars & Trucks": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images", "Brand/Model", "Year", "Mileage"],
  "Motorcycles": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images", "Brand/Model", "Year", "Mileage"],
  "Boats & Marine": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images", "Brand/Model", "Year", "Mileage"],
  "RVs & Campers": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images", "Brand/Model", "Year", "Mileage"],
  "Houses for Sale": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images", "Property Type", "Bedrooms", "Bathrooms"],
  "Apartments for Rent": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images", "Property Type", "Bedrooms", "Bathrooms"],
  "Commercial Property": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images", "Property Type", "Bedrooms", "Bathrooms"],
  "Vacation Rentals": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images", "Property Type", "Bedrooms", "Bathrooms"],
  "Jobs": ["Title", "Description", "Location", "Contact Info", "Job Type"],
  "Services": ["Title", "Description", "Location", "Contact Info", "Service Type"],
  "Fashion": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images", "Brand/Model"],
  "Home & Garden": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images"],
  "Sports": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images"],
  "Books": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images", "Author", "Genre"],
  "Pets": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images", "Pet Type", "Breed", "Age"],
  "Food & Dining": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images"],
  "Travel & Resorts": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images"],
  "Deals & Offers": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images"],
  "Tickets": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images", "Event Date", "Venue"],
  "Events & Shows": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images", "Event Date", "Venue"],
  "Auction": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images", "Auction End"],
  "Buy & Sell": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images"],
  "Notices": ["Title", "Description", "Location", "Contact Info", "Notice Type"],
  "Health & Beauty": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images"],
  "Baby & Kids": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images"],
  "Arts & Crafts": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images"],
  "Musical Instruments": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images", "Instrument Type"],
  "Office Supplies": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images"],
  "Digital Products": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images", "Digital Format"],
  "Software & Apps": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images"],
  "Tutoring & Lessons": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images", "Lesson Type"],
  "Home Repair": ["Title", "Description", "Price", "Price Type", "Location", "Contact Info", "Images", "Repair Type"],
  "Free": ["Title", "Description", "Location", "Contact Info", "Images"],
  "Other": ["Title", "Description", "Price", "Price Type", "Condition", "Location", "Contact Info", "Images"]
};
