import { CategoryType } from '../types';

// Categories will be fetched from backend via categoryService
// These are fallbacks for TypeScript type checking
export const CATEGORY_COLORS: Record<string, string> = {};

export const CATEGORIES: CategoryType[] = [];

// Helper to convert backend category to Tailwind class
export const getCategoryColor = (category: string, color: string): string => {
  return `bg-${color}-600`;
};

export const COUNTRIES = [
  'United States',
  'Canada',
  'United Kingdom',
  'Australia',
  'India',
  'Germany',
  'France',
  'Spain',
  'Italy',
  'Brazil',
  'Mexico',
  'Japan',
  'China',
  'South Korea',
  'Singapore',
  'UAE',
  'Saudi Arabia',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Egypt',
  'Argentina',
  'Chile',
  'Colombia',
  'Netherlands',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Turkey',
  'Thailand',
  'Malaysia',
  'Indonesia',
  'Philippines',
  'Vietnam',
  'New Zealand',
  'Ireland',
  'Switzerland',
  'Austria',
  'Belgium',
  'Portugal',
  'Greece',
  'Czech Republic',
  'Romania',
  'Hungary',
  'Israel',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
];

export const STATES: Record<string, string[]> = {
  'United States': ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
  'Canada': ['Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador', 'Northwest Territories', 'Nova Scotia', 'Nunavut', 'Ontario', 'Prince Edward Island', 'Quebec', 'Saskatchewan', 'Yukon'],
  'United Kingdom': ['England', 'Scotland', 'Wales', 'Northern Ireland'],
  'Australia': ['New South Wales', 'Victoria', 'Queensland', 'South Australia', 'Western Australia', 'Tasmania', 'Northern Territory', 'Australian Capital Territory'],
  'India': ['Andhra Pradesh', 'Delhi', 'Gujarat', 'Karnataka', 'Kerala', 'Maharashtra', 'Tamil Nadu', 'Telangana', 'West Bengal', 'Uttar Pradesh', 'Rajasthan', 'Punjab (India)', 'Haryana'],
  'Germany': ['Bavaria', 'Berlin', 'Hamburg', 'Hesse', 'North Rhine-Westphalia', 'Saxony', 'Baden-Württemberg'],
  'France': ['Île-de-France', 'Provence-Alpes-Côte d\'Azur', 'Auvergne-Rhône-Alpes', 'Nouvelle-Aquitaine', 'Occitanie', 'Hauts-de-France', 'Brittany'],
  'Spain': ['Madrid', 'Catalonia', 'Andalusia', 'Valencia', 'Galicia', 'Castile and León', 'Basque Country'],
  'Italy': ['Lazio', 'Lombardy', 'Campania', 'Sicily', 'Veneto', 'Piedmont', 'Emilia-Romagna'],
  'Brazil': ['São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Bahia', 'Paraná', 'Rio Grande do Sul', 'Pernambuco'],
  'Mexico': ['Mexico City', 'Jalisco', 'Nuevo León', 'Puebla', 'Guanajuato', 'Chiapas', 'Veracruz'],
  'Japan': ['Tokyo', 'Osaka', 'Kanagawa', 'Aichi', 'Hokkaido', 'Fukuoka', 'Kyoto'],
  'China': ['Beijing', 'Shanghai', 'Guangdong', 'Zhejiang', 'Jiangsu', 'Sichuan', 'Hubei'],
  'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Gyeonggi'],
  'Singapore': ['Central Region', 'East Region', 'North Region', 'North-East Region', 'West Region'],
  'UAE': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain'],
  'Saudi Arabia': ['Riyadh', 'Makkah', 'Eastern Province', 'Medina', 'Asir', 'Qassim', 'Tabuk'],
  'South Africa': ['Gauteng', 'Western Cape', 'KwaZulu-Natal', 'Eastern Cape', 'Limpopo', 'Mpumalanga', 'North West'],
  'Nigeria': ['Lagos', 'Kano', 'Rivers', 'Kaduna', 'Oyo', 'Abuja', 'Delta'],
  'Kenya': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika', 'Malindi'],
  'Egypt': ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor'],
  'Argentina': ['Buenos Aires', 'Córdoba', 'Santa Fe', 'Mendoza', 'Tucumán', 'Salta', 'Entre Ríos'],
  'Chile': ['Santiago', 'Valparaíso', 'Biobío', 'Araucanía', 'Los Lagos', 'Maule', 'Antofagasta'],
  'Colombia': ['Bogotá', 'Antioquia', 'Valle del Cauca', 'Atlántico', 'Santander', 'Bolívar', 'Cundinamarca'],
  'Netherlands': ['North Holland', 'South Holland', 'Utrecht', 'North Brabant', 'Gelderland', 'Overijssel', 'Limburg'],
  'Sweden': ['Stockholm', 'Västra Götaland', 'Skåne', 'Uppsala', 'Östergötland', 'Halland', 'Jönköping'],
  'Norway': ['Oslo', 'Viken', 'Vestland', 'Trøndelag', 'Rogaland', 'Innlandet', 'Vestfold og Telemark'],
  'Denmark': ['Capital Region', 'Zealand', 'Southern Denmark', 'Central Denmark', 'North Denmark'],
  'Finland': ['Uusimaa', 'Pirkanmaa', 'Southwest Finland', 'North Ostrobothnia', 'Central Finland', 'Päijänne Tavastia'],
  'Poland': ['Masovian', 'Silesian', 'Greater Poland', 'Lesser Poland', 'Lower Silesian', 'Łódź', 'Pomeranian'],
  'Turkey': ['Istanbul', 'Ankara', 'İzmir', 'Bursa', 'Antalya', 'Adana', 'Konya'],
  'Thailand': ['Bangkok', 'Chiang Mai', 'Nonthaburi', 'Nakhon Ratchasima', 'Chon Buri', 'Songkhla', 'Pathum Thani'],
  'Malaysia': ['Kuala Lumpur', 'Selangor', 'Johor', 'Penang', 'Perak', 'Sabah', 'Sarawak'],
  'Indonesia': ['Jakarta', 'West Java', 'East Java', 'Central Java', 'North Sumatra', 'Banten', 'South Sulawesi'],
  'Philippines': ['Metro Manila', 'Calabarzon', 'Central Luzon', 'Central Visayas', 'Western Visayas', 'Davao Region', 'Ilocos Region'],
  'Vietnam': ['Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Hai Phong', 'Can Tho', 'Bien Hoa', 'Nha Trang'],
  'New Zealand': ['Auckland', 'Wellington', 'Canterbury', 'Waikato', 'Bay of Plenty', 'Otago', 'Manawatu-Wanganui'],
  'Ireland': ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford', 'Kildare', 'Meath'],
  'Switzerland': ['Zürich', 'Bern', 'Vaud', 'Geneva', 'Aargau', 'Ticino', 'Basel-Stadt'],
  'Austria': ['Vienna', 'Lower Austria', 'Upper Austria', 'Styria', 'Tyrol', 'Salzburg', 'Carinthia'],
  'Belgium': ['Flemish Brabant', 'Antwerp', 'East Flanders', 'West Flanders', 'Liège', 'Brussels', 'Hainaut'],
  'Portugal': ['Lisbon', 'Porto', 'Faro', 'Setúbal', 'Braga', 'Coimbra', 'Aveiro'],
  'Greece': ['Attica', 'Central Macedonia', 'Crete', 'Thessaly', 'Western Greece', 'Peloponnese', 'Epirus'],
  'Czech Republic': ['Prague', 'Central Bohemia', 'South Moravia', 'Moravian-Silesian', 'Olomouc', 'Plzeň', 'South Bohemia'],
  'Romania': ['Bucharest', 'Cluj', 'Timiș', 'Iași', 'Constanța', 'Brașov', 'Prahova'],
  'Hungary': ['Budapest', 'Pest', 'Borsod-Abaúj-Zemplén', 'Hajdú-Bihar', 'Győr-Moson-Sopron', 'Csongrád', 'Szabolcs-Szatmár-Bereg'],
  'Israel': ['Tel Aviv', 'Jerusalem', 'Haifa', 'Central', 'Southern', 'Northern'],
  'Pakistan': ['Punjab (Pakistan)', 'Sindh', 'Khyber Pakhtunkhwa', 'Balochistan', 'Islamabad Capital Territory', 'Gilgit-Baltistan', 'Azad Kashmir'],
  'Bangladesh': ['Dhaka', 'Chittagong', 'Rajshahi', 'Khulna', 'Sylhet', 'Barisal', 'Rangpur'],
  'Sri Lanka': ['Western', 'Central', 'Southern', 'Northern', 'Eastern', 'North Western', 'Sabaragamuwa'],
};

export const CITIES: Record<string, string[]> = {
  // United States (major cities for each state)
  'Alabama': ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville'],
  'Alaska': ['Anchorage', 'Fairbanks', 'Juneau', 'Sitka'],
  'Arizona': ['Phoenix', 'Tucson', 'Mesa', 'Scottsdale'],
  'Arkansas': ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale'],
  'California': ['Los Angeles', 'San Francisco', 'San Diego', 'San Jose', 'Sacramento', 'Oakland', 'Fresno', 'Long Beach'],
  'Colorado': ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins'],
  'Connecticut': ['Bridgeport', 'New Haven', 'Hartford', 'Stamford'],
  'Delaware': ['Wilmington', 'Dover', 'Newark', 'Middletown'],
  'Florida': ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Fort Lauderdale', 'Tallahassee'],
  'Georgia': ['Atlanta', 'Augusta', 'Columbus', 'Savannah'],
  'Hawaii': ['Honolulu', 'Pearl City', 'Hilo', 'Kailua'],
  'Idaho': ['Boise', 'Meridian', 'Nampa', 'Idaho Falls'],
  'Illinois': ['Chicago', 'Aurora', 'Naperville', 'Rockford', 'Joliet'],
  'Indiana': ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend'],
  'Iowa': ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City'],
  'Kansas': ['Wichita', 'Overland Park', 'Kansas City', 'Topeka'],
  'Kentucky': ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro'],
  'Louisiana': ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette'],
  'Maine': ['Portland', 'Lewiston', 'Bangor', 'South Portland'],
  'Maryland': ['Baltimore', 'Frederick', 'Rockville', 'Gaithersburg'],
  'Massachusetts': ['Boston', 'Worcester', 'Springfield', 'Cambridge'],
  'Michigan': ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights'],
  'Minnesota': ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth'],
  'Mississippi': ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg'],
  'Missouri': ['Kansas City', 'St. Louis', 'Springfield', 'Columbia'],
  'Montana': ['Billings', 'Missoula', 'Great Falls', 'Bozeman'],
  'Nebraska': ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island'],
  'Nevada': ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas'],
  'New Hampshire': ['Manchester', 'Nashua', 'Concord', 'Derry'],
  'New Jersey': ['Newark', 'Jersey City', 'Paterson', 'Elizabeth'],
  'New Mexico': ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe'],
  'New York': ['New York City', 'Buffalo', 'Rochester', 'Albany', 'Syracuse'],
  'North Carolina': ['Charlotte', 'Raleigh', 'Greensboro', 'Durham'],
  'North Dakota': ['Fargo', 'Bismarck', 'Grand Forks', 'Minot'],
  'Ohio': ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo'],
  'Oklahoma': ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow'],
  'Oregon': ['Portland', 'Salem', 'Eugene', 'Gresham'],
  'Pennsylvania': ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie'],
  'Rhode Island': ['Providence', 'Warwick', 'Cranston', 'Pawtucket'],
  'South Carolina': ['Columbia', 'Charleston', 'North Charleston', 'Mount Pleasant'],
  'South Dakota': ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings'],
  'Tennessee': ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga'],
  'Texas': ['Houston', 'Austin', 'Dallas', 'San Antonio', 'Fort Worth', 'El Paso'],
  'Utah': ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan'],
  'Vermont': ['Burlington', 'South Burlington', 'Rutland', 'Barre'],
  'Virginia': ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond'],
  'Washington': ['Seattle', 'Spokane', 'Tacoma', 'Vancouver'],
  'West Virginia': ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg'],
  'Wisconsin': ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha'],
  'Wyoming': ['Cheyenne', 'Casper', 'Laramie', 'Gillette'],
  
  // Canada
  'Alberta': ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge'],
  'British Columbia': ['Vancouver', 'Victoria', 'Surrey', 'Burnaby'],
  'Manitoba': ['Winnipeg', 'Brandon', 'Steinbach', 'Thompson'],
  'New Brunswick': ['Moncton', 'Saint John', 'Fredericton', 'Dieppe'],
  'Newfoundland and Labrador': ['St. John\'s', 'Mount Pearl', 'Corner Brook', 'Conception Bay South'],
  'Northwest Territories': ['Yellowknife', 'Hay River', 'Inuvik', 'Fort Smith'],
  'Nova Scotia': ['Halifax', 'Cape Breton', 'Truro', 'New Glasgow'],
  'Nunavut': ['Iqaluit', 'Rankin Inlet', 'Arviat', 'Baker Lake'],
  'Ontario': ['Toronto', 'Ottawa', 'Mississauga', 'Hamilton', 'London', 'Windsor'],
  'Prince Edward Island': ['Charlottetown', 'Summerside', 'Stratford', 'Cornwall'],
  'Quebec': ['Montreal', 'Quebec City', 'Laval', 'Gatineau'],
  'Saskatchewan': ['Saskatoon', 'Regina', 'Prince Albert', 'Moose Jaw'],
  'Yukon': ['Whitehorse', 'Dawson City', 'Watson Lake', 'Haines Junction'],
  
  // UK
  'England': ['London', 'Manchester', 'Birmingham', 'Liverpool', 'Leeds', 'Sheffield', 'Bristol'],
  'Scotland': ['Edinburgh', 'Glasgow', 'Aberdeen', 'Dundee'],
  'Wales': ['Cardiff', 'Swansea', 'Newport', 'Wrexham'],
  'Northern Ireland': ['Belfast', 'Derry', 'Lisburn', 'Newry'],
  
  // Australia
  'New South Wales': ['Sydney', 'Newcastle', 'Wollongong', 'Central Coast'],
  'Victoria': ['Melbourne', 'Geelong', 'Ballarat', 'Bendigo'],
  'Queensland': ['Brisbane', 'Gold Coast', 'Sunshine Coast', 'Townsville'],
  'South Australia': ['Adelaide', 'Mount Gambier', 'Whyalla', 'Murray Bridge'],
  'Western Australia': ['Perth', 'Mandurah', 'Bunbury', 'Albany'],
  'Tasmania': ['Hobart', 'Launceston', 'Devonport', 'Burnie'],
  'Northern Territory': ['Darwin', 'Alice Springs', 'Palmerston', 'Katherine'],
  'Australian Capital Territory': ['Canberra', 'Queanbeyan', 'Gungahlin', 'Tuggeranong'],
  
  // India
  'Andhra Pradesh': ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore'],
  'Delhi': ['New Delhi', 'Delhi', 'Dwarka', 'Rohini'],
  'Gujarat': ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot'],
  'Karnataka': ['Bangalore', 'Mysore', 'Hubli', 'Mangalore'],
  'Kerala': ['Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Thrissur'],
  'Maharashtra': ['Mumbai', 'Pune', 'Nagpur', 'Thane'],
  'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli'],
  'Telangana': ['Hyderabad', 'Warangal', 'Nizamabad', 'Khammam'],
  'West Bengal': ['Kolkata', 'Howrah', 'Durgapur', 'Asansol'],
  'Uttar Pradesh': ['Lucknow', 'Kanpur', 'Agra', 'Varanasi'],
  'Rajasthan': ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota'],
  'Punjab (India)': ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala'],
  'Haryana': ['Gurgaon', 'Faridabad', 'Panipat', 'Ambala'],
  
  // Other countries (major cities)
  'Bavaria': ['Munich', 'Nuremberg', 'Augsburg', 'Regensburg'],
  'Berlin': ['Berlin'],
  'Hamburg': ['Hamburg'],
  'Hesse': ['Frankfurt', 'Wiesbaden', 'Kassel', 'Darmstadt'],
  'North Rhine-Westphalia': ['Cologne', 'Düsseldorf', 'Dortmund', 'Essen'],
  'Saxony': ['Dresden', 'Leipzig', 'Chemnitz', 'Zwickau'],
  'Baden-Württemberg': ['Stuttgart', 'Mannheim', 'Karlsruhe', 'Freiburg'],
  
  'Île-de-France': ['Paris', 'Versailles', 'Saint-Denis', 'Nanterre'],
  'Provence-Alpes-Côte d\'Azur': ['Marseille', 'Nice', 'Toulon', 'Aix-en-Provence'],
  'Auvergne-Rhône-Alpes': ['Lyon', 'Grenoble', 'Saint-Étienne', 'Annecy'],
  'Nouvelle-Aquitaine': ['Bordeaux', 'Limoges', 'Poitiers', 'La Rochelle'],
  'Occitanie': ['Toulouse', 'Montpellier', 'Nîmes', 'Perpignan'],
  'Hauts-de-France': ['Lille', 'Amiens', 'Roubaix', 'Tourcoing'],
  'Brittany': ['Rennes', 'Brest', 'Quimper', 'Saint-Malo'],
  
  'Madrid': ['Madrid', 'Móstoles', 'Alcalá de Henares', 'Fuenlabrada'],
  'Catalonia': ['Barcelona', 'Hospitalet', 'Badalona', 'Terrassa'],
  'Andalusia': ['Seville', 'Málaga', 'Córdoba', 'Granada'],
  'Valencia': ['Valencia', 'Alicante', 'Elche', 'Castellón'],
  'Galicia': ['Vigo', 'A Coruña', 'Ourense', 'Santiago de Compostela'],
  'Castile and León': ['Valladolid', 'Burgos', 'Salamanca', 'León'],
  'Basque Country': ['Bilbao', 'Vitoria-Gasteiz', 'San Sebastián', 'Barakaldo'],
  
  'Lazio': ['Rome', 'Latina', 'Frosinone', 'Viterbo'],
  'Lombardy': ['Milan', 'Bergamo', 'Brescia', 'Monza'],
  'Campania': ['Naples', 'Salerno', 'Caserta', 'Benevento'],
  'Sicily': ['Palermo', 'Catania', 'Messina', 'Syracuse'],
  'Veneto': ['Venice', 'Verona', 'Padua', 'Vicenza'],
  'Piedmont': ['Turin', 'Novara', 'Alessandria', 'Asti'],
  'Emilia-Romagna': ['Bologna', 'Modena', 'Parma', 'Ravenna'],
  
  'São Paulo': ['São Paulo', 'Campinas', 'Santos', 'São Bernardo do Campo'],
  'Rio de Janeiro': ['Rio de Janeiro', 'Niterói', 'Duque de Caxias', 'Nova Iguaçu'],
  'Minas Gerais': ['Belo Horizonte', 'Uberlândia', 'Contagem', 'Juiz de Fora'],
  'Bahia': ['Salvador', 'Feira de Santana', 'Vitória da Conquista', 'Camaçari'],
  'Paraná': ['Curitiba', 'Londrina', 'Maringá', 'Ponta Grossa'],
  'Rio Grande do Sul': ['Porto Alegre', 'Caxias do Sul', 'Pelotas', 'Canoas'],
  'Pernambuco': ['Recife', 'Jaboatão dos Guararapes', 'Olinda', 'Caruaru'],
  
  'Mexico City': ['Mexico City', 'Iztapalapa', 'Ecatepec', 'Nezahualcóyotl'],
  'Jalisco': ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Tonalá'],
  'Nuevo León': ['Monterrey', 'Guadalupe', 'San Nicolás', 'Apodaca'],
  'Puebla': ['Puebla', 'Tehuacán', 'Cholula', 'Atlixco'],
  'Guanajuato': ['León', 'Irapuato', 'Celaya', 'Salamanca'],
  'Chiapas': ['Tuxtla Gutiérrez', 'Tapachula', 'San Cristóbal', 'Comitán'],
  'Veracruz': ['Veracruz', 'Xalapa', 'Coatzacoalcos', 'Poza Rica'],
  
  'Tokyo': ['Tokyo', 'Shibuya', 'Shinjuku', 'Yokohama'],
  'Osaka': ['Osaka', 'Sakai', 'Higashiosaka', 'Toyonaka'],
  'Kanagawa': ['Yokohama', 'Kawasaki', 'Sagamihara', 'Fujisawa'],
  'Aichi': ['Nagoya', 'Toyota', 'Okazaki', 'Ichinomiya'],
  'Hokkaido': ['Sapporo', 'Asahikawa', 'Hakodate', 'Kushiro'],
  'Fukuoka': ['Fukuoka', 'Kitakyushu', 'Kurume', 'Omuta'],
  'Kyoto': ['Kyoto', 'Uji', 'Kameoka', 'Nagaokakyo'],
  
  'Beijing': ['Beijing', 'Chaoyang', 'Haidian', 'Fengtai'],
  'Shanghai': ['Shanghai', 'Pudong', 'Minhang', 'Baoshan'],
  'Guangdong': ['Guangzhou', 'Shenzhen', 'Dongguan', 'Foshan'],
  'Zhejiang': ['Hangzhou', 'Ningbo', 'Wenzhou', 'Shaoxing'],
  'Jiangsu': ['Nanjing', 'Suzhou', 'Wuxi', 'Changzhou'],
  'Sichuan': ['Chengdu', 'Mianyang', 'Deyang', 'Nanchong'],
  'Hubei': ['Wuhan', 'Yichang', 'Xiangyang', 'Jingzhou'],
  
  'Seoul': ['Seoul', 'Gangnam', 'Songpa', 'Seocho'],
  'Busan': ['Busan', 'Haeundae', 'Suyeong', 'Busanjin'],
  'Incheon': ['Incheon', 'Namdong', 'Bupyeong', 'Seo'],
  'Daegu': ['Daegu', 'Suseong', 'Dalseo', 'Buk'],
  'Daejeon': ['Daejeon', 'Yuseong', 'Seo', 'Daedeok'],
  'Gwangju': ['Gwangju', 'Buk', 'Nam', 'Seo'],
  'Gyeonggi': ['Suwon', 'Seongnam', 'Goyang', 'Yongin'],
  
  'Central Region': ['Singapore City', 'Orchard', 'Marina Bay', 'Raffles Place'],
  'East Region': ['Tampines', 'Bedok', 'Pasir Ris', 'Simei'],
  'North Region': ['Woodlands', 'Yishun', 'Sembawang', 'Admiralty'],
  'North-East Region': ['Hougang', 'Sengkang', 'Punggol', 'Serangoon'],
  'West Region': ['Jurong', 'Clementi', 'Bukit Batok', 'Choa Chu Kang'],
  
  'Dubai': ['Dubai', 'Deira', 'Bur Dubai', 'Jumeirah'],
  'Abu Dhabi': ['Abu Dhabi', 'Al Ain', 'Khalifa City', 'Yas Island'],
  'Sharjah': ['Sharjah', 'Al Nahda', 'Al Majaz', 'Al Qasimia'],
  'Ajman': ['Ajman', 'Al Nuaimiya', 'Al Rashidiya', 'Al Bustan'],
  'Ras Al Khaimah': ['Ras Al Khaimah', 'Al Nakheel', 'Dafan Al Nakheel', 'Al Hamra'],
  'Fujairah': ['Fujairah', 'Dibba', 'Khor Fakkan', 'Kalba'],
  'Umm Al Quwain': ['Umm Al Quwain', 'Falaj Al Mualla', 'Old Harbour', 'Al Raas'],
  
  'Riyadh': ['Riyadh', 'Al Olaya', 'Al Malaz', 'Al Wurud'],
  'Makkah': ['Mecca', 'Jeddah', 'Taif', 'Rabigh'],
  'Eastern Province': ['Dammam', 'Khobar', 'Dhahran', 'Jubail'],
  'Medina': ['Medina', 'Yanbu', 'Badr', 'Al Ula'],
  'Asir': ['Abha', 'Khamis Mushait', 'Bisha', 'Najran'],
  'Qassim': ['Buraidah', 'Unaizah', 'Al Rass', 'Al Mithnab'],
  'Tabuk': ['Tabuk', 'Al Wajh', 'Duba', 'Haql'],
  
  'Gauteng': ['Johannesburg', 'Pretoria', 'Soweto', 'Sandton'],
  'Western Cape': ['Cape Town', 'Stellenbosch', 'Paarl', 'George'],
  'KwaZulu-Natal': ['Durban', 'Pietermaritzburg', 'Richards Bay', 'Newcastle'],
  'Eastern Cape': ['Port Elizabeth', 'East London', 'Mthatha', 'Queenstown'],
  'Limpopo': ['Polokwane', 'Tzaneen', 'Mokopane', 'Thohoyandou'],
  'Mpumalanga': ['Nelspruit', 'Witbank', 'Middelburg', 'Secunda'],
  'North West': ['Rustenburg', 'Mahikeng', 'Klerksdorp', 'Potchefstroom'],
  
  'Lagos': ['Lagos', 'Ikeja', 'Lekki', 'Victoria Island'],
  'Kano': ['Kano', 'Fagge', 'Nassarawa', 'Gwale'],
  'Rivers': ['Port Harcourt', 'Obio-Akpor', 'Eleme', 'Okrika'],
  'Kaduna': ['Kaduna', 'Zaria', 'Kafanchan', 'Kagoro'],
  'Oyo': ['Ibadan', 'Ogbomoso', 'Oyo', 'Iseyin'],
  'Abuja': ['Abuja', 'Gwagwalada', 'Kuje', 'Bwari'],
  'Delta': ['Warri', 'Asaba', 'Sapele', 'Ughelli'],
  
  'Nairobi': ['Nairobi', 'Westlands', 'Karen', 'Kilimani'],
  'Mombasa': ['Mombasa', 'Nyali', 'Bamburi', 'Likoni'],
  'Kisumu': ['Kisumu', 'Kondele', 'Migosi', 'Mamboleo'],
  'Nakuru': ['Nakuru', 'Naivasha', 'Gilgil', 'Molo'],
  'Eldoret': ['Eldoret', 'Langas', 'Pioneer', 'Kapsoya'],
  'Thika': ['Thika', 'Juja', 'Ruiru', 'Gatundu'],
  'Malindi': ['Malindi', 'Watamu', 'Gede', 'Mambrui'],
  
  'Cairo': ['Cairo', 'Giza', 'Heliopolis', 'Nasr City'],
  'Alexandria': ['Alexandria', 'Montaza', 'Borg El Arab', 'Agami'],
  'Giza': ['Giza', '6th of October', 'Sheikh Zayed', 'Dokki'],
  'Shubra El Kheima': ['Shubra El Kheima', 'Qalyub', 'Shubra', 'Mostorod'],
  'Port Said': ['Port Said', 'Port Fuad', 'Al Arab', 'Al Manakh'],
  'Suez': ['Suez', 'Ain Sokhna', 'Ataqah', 'Faisal'],
  'Luxor': ['Luxor', 'Karnak', 'West Bank', 'East Bank'],
  
  // Add more global cities as needed
  'Buenos Aires': ['Buenos Aires', 'La Plata', 'Mar del Plata', 'Quilmes'],
  'Córdoba': ['Córdoba', 'Villa María', 'Río Cuarto', 'Villa Carlos Paz'],
  'Santiago': ['Santiago', 'Providencia', 'Las Condes', 'Maipú'],
  'Bogotá': ['Bogotá', 'Suba', 'Kennedy', 'Engativá'],
  'North Holland': ['Amsterdam', 'Haarlem', 'Zaanstad', 'Haarlemmermeer'],
  'South Holland': ['Rotterdam', 'The Hague', 'Leiden', 'Dordrecht'],
  'Stockholm': ['Stockholm', 'Solna', 'Sundbyberg', 'Nacka'],
  'Oslo': ['Oslo', 'Bærum', 'Asker', 'Drammen'],
  'Capital Region': ['Copenhagen', 'Frederiksberg', 'Gentofte', 'Gladsaxe'],
  'Uusimaa': ['Helsinki', 'Espoo', 'Vantaa', 'Kauniainen'],
  'Masovian': ['Warsaw', 'Radom', 'Płock', 'Siedlce'],
  'Istanbul': ['Istanbul', 'Kadıköy', 'Beşiktaş', 'Üsküdar'],
  'Bangkok': ['Bangkok', 'Chatuchak', 'Bang Khen', 'Lat Krabang'],
  'Kuala Lumpur': ['Kuala Lumpur', 'Cheras', 'Sentul', 'Bukit Jalil'],
  'Jakarta': ['Jakarta', 'Central Jakarta', 'South Jakarta', 'West Jakarta'],
  'Metro Manila': ['Manila', 'Quezon City', 'Makati', 'Pasig'],
  'Hanoi': ['Hanoi', 'Ba Dinh', 'Hoan Kiem', 'Dong Da'],
  'Ho Chi Minh City': ['Ho Chi Minh City', 'District 1', 'District 3', 'Binh Thanh'],
  'Auckland': ['Auckland', 'North Shore', 'Manukau', 'Waitakere'],
  'Wellington': ['Wellington', 'Lower Hutt', 'Upper Hutt', 'Porirua'],
  'Dublin': ['Dublin', 'Dún Laoghaire', 'Fingal', 'South Dublin'],
  'Zürich': ['Zürich', 'Winterthur', 'Uster', 'Dübendorf'],
  'Vienna': ['Vienna', 'Graz', 'Linz', 'Salzburg'],
  'Flemish Brabant': ['Leuven', 'Aalst', 'Vilvoorde', 'Tienen'],
  'Lisbon': ['Lisbon', 'Amadora', 'Almada', 'Sintra'],
  'Attica': ['Athens', 'Piraeus', 'Peristeri', 'Kallithea'],
  'Prague': ['Prague', 'Prague 1', 'Prague 2', 'Prague 3'],
  'Bucharest': ['Bucharest', 'Sector 1', 'Sector 2', 'Sector 3'],
  'Budapest': ['Budapest', 'Debrecen', 'Szeged', 'Miskolc'],
  'Tel Aviv': ['Tel Aviv', 'Ramat Gan', 'Holon', 'Bat Yam'],
  'Jerusalem': ['Jerusalem', 'Beitar Illit', 'Modi\'in Illit', 'Ma\'ale Adumim'],
  'Punjab (Pakistan)': ['Lahore', 'Faisalabad', 'Rawalpindi', 'Multan'],
  'Sindh': ['Karachi', 'Hyderabad', 'Sukkur', 'Larkana'],
  'Khyber Pakhtunkhwa': ['Peshawar', 'Mardan', 'Abbottabad', 'Swat'],
  'Balochistan': ['Quetta', 'Turbat', 'Khuzdar', 'Chaman'],
  'Islamabad Capital Territory': ['Islamabad', 'Rawalpindi'],
  'Dhaka': ['Dhaka', 'Gazipur', 'Narayanganj', 'Tongi'],
  'Chittagong': ['Chittagong', 'Cox\'s Bazar', 'Comilla', 'Brahmanbaria'],
  'Rajshahi': ['Rajshahi', 'Bogra', 'Pabna', 'Sirajganj'],
  'Khulna': ['Khulna', 'Jessore', 'Kushtia', 'Satkhira'],
  'Sylhet': ['Sylhet', 'Moulvibazar', 'Habiganj', 'Sunamganj'],
  'Western': ['Colombo', 'Gampaha', 'Kalutara', 'Negombo'],
  'Central': ['Kandy', 'Matale', 'Nuwara Eliya'],
  'Southern': ['Galle', 'Matara', 'Hambantota'],
};

export const CURRENCIES = [
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc' },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'MXN', symbol: '$', name: 'Mexican Peso' },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
  { code: 'RUB', symbol: '₽', name: 'Russian Ruble' },
  { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone' },
  { code: 'PLN', symbol: 'zł', name: 'Polish Złoty' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira' },
  { code: 'THB', symbol: '฿', name: 'Thai Baht' },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
  { code: 'ILS', symbol: '₪', name: 'Israeli Shekel' },
  { code: 'CLP', symbol: '$', name: 'Chilean Peso' },
  { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal' },
  { code: 'EGP', symbol: '£', name: 'Egyptian Pound' },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
  { code: 'ARS', symbol: '$', name: 'Argentine Peso' },
  { code: 'COP', symbol: '$', name: 'Colombian Peso' },
  { code: 'VND', symbol: '₫', name: 'Vietnamese Dong' },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu' },
  { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia' },
  { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee' },
];

export const ADS_PER_PAGE = 24;

export const MAX_IMAGES = 5;
export const MAX_IMAGE_SIZE = 5 * 1024 * 1024; // 5MB

export const ROUTES = {
  HOME: '/',
  AD_DETAIL: '/ad/:id',
  POST_AD: '/post-ad',
  DASHBOARD: '/dashboard',
  LOGIN: '/login',
  PRICING: '/pricing',
} as const;
